language: python

branches:
  only:
    - master

sudo: required
services:
  - docker

cache:
  - pip
  - directories:
    - node_modules
    - ecommerce/static/bower_components

addons:
  apt:
    packages:
      - lcov

before_install:
  - docker-compose -f ./.travis/docker-compose-travis.yml up -d

install:
  - docker exec -t ecommerce_testing bash -c "
      cd /edx/app/ecommerce/ecommerce/ &&
      pip install tox
    "
script:
  - docker exec -t -e TRAVIS=1 ecommerce_testing bash -c "
      cd /edx/app/ecommerce/ecommerce/ &&
      PATH=\$PATH:/edx/app/ecommerce/nodeenvs/ecommerce/bin:/snap/bin
      make $TARGETS
    "

matrix:
  include:
    - python: 2.7
      env:
        TESTNAME=quality-and-js
        TARGETS="PYTHON_ENV=py27 requirements.js check_translations_up_to_date validate_translations clean_static static quality validate_js"
    - python: 2.7
      env: TESTNAME=test-python TARGETS="PYTHON_ENV=py27 requirements.js clean_static static validate_python"
    - python: 3.5
      env:
        TESTNAME=quality-and-js-.3.5
        TARGETS="PYTHON_ENV=py35 requirements.js check_translations_up_to_date validate_translations clean_static static quality validate_js"
    - python: 3.5
      env: TESTNAME=test-python-3.5 TARGETS="PYTHON_ENV=py35 requirements.js clean_static static validate_python"
      after_success:
        - pip install -U codecov
        - docker exec ecommerce_testing /edx/app/ecommerce/ecommerce/.travis/run_coverage.sh
        - codecov

