# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20191115_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Country'),
        ),
    ]
