# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200117_1312'),
        ('core', '0059_user_country'),
    ]

    operations = [
    ]
