# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20200116_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='card_type',
            field=models.CharField(blank=True, choices=[('american_express', 'American Express'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('discover', 'Discover')], max_length=255, null=True),
        ),
    ]
