# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_auto_20200118_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='card_type',
            field=models.CharField(blank=True, choices=[('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('visa', 'Visa')], max_length=255, null=True),
        ),
    ]
