# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_card_type_ordering'),
        ('payment', '0029_auto_20200125_0509'),
    ]

    operations = [
    ]
