# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_auto_20200125_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='card_type',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('discover', 'Discover'), ('american_express', 'American Express'), ('mastercard', 'MasterCard')], max_length=255, null=True),
        ),
    ]
